import socket

HOST = socket.gethostname()
PORT = 2445
MAX_CONNECTIONS = 5
MAX_BUFFER_SIZE = 1024

CERT_FILE = './cert.pem'
KEY_FILE = CERT_FILE

DB_FILENAME = 'old_trusty.db'
DB_TABLENAME_FILES = 'file_cert_map'
DB_TABLENAME_KEYS = 'file_key_map'
DB_TABLES = [
    DB_TABLENAME_FILES,
    DB_TABLENAME_KEYS,
]

MAX_FILENAME_LENGTH = 200

LOGGING_ENABLED = True

FILES_FOLDER = 'files'
CERTS_FOLDER = 'certs'
REQUIRED_FOLDERS = [
    FILES_FOLDER,
    CERTS_FOLDER,
]

ENCRYPTED_FILE_POSTFIX = '.lock'
